"""increase_api_key_length

Revision ID: 3580c0dcd005
Revises: e214adf7fb66
Create Date: 2024-01-20 14:25:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3580c0dcd005'
down_revision: Union[str, None] = 'e214adf7fb66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'key',
               existing_type=sa.String(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'key',
               existing_type=sa.String(length=128),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###
